from bicycles import db

class BicycleCount(db.Model):
    X = db.Column(db.Numeric)
    Y = db.Column(db.Numeric)
    ObjectID = db.Column(db.Integer)
    RecordNum = db.Column(db.Integer, primary_key=True)
    SETDate = db.Column(db.DateTime)
    SETYear = db.Column(db.Integer)
    Comments = db.Column(db.Text)
    MCD = db.Column(db.BigInteger)
    Route = db.Column(db.Integer)
    Road = db.Column(db.Text)
    CntDir = db.Column(db.String(4))
    FromLmt = db.Column(db.Text)
    ToLmt = db.Column(db.Text)
    Type = db.Column(db.Text)
    Latitude = db.Column(db.Numeric)
    Longitude = db.Column(db.Numeric)
    Factor = db.Column(db.Integer)
    Axle = db.Column(db.Float)
    OutDir = db.Column(db.String(1))
    InDir = db.Column(db.String(1))
    AADB = db.Column(db.Integer)
    Updated = db.Column(db.DateTime)
    Co_name = db.Column(db.Text)
    Mun_name = db.Column(db.Text)
    GlobalID = db.Column(db.Text)
    Program = db.Column(db.Text)
    BikePedGro = db.Column(db.Text)
    BikePedFac = db.Column(db.Text)


class Weather(db.Model):
    Station = db.Column(db.Text)
    Name = db.Column(db.Text)
    Date = db.Column(db.Date, primary_key=True)
    Prcp = db.Column(db.Float)
    Tavg = db.Column(db.Integer)
    Tmax = db.Column(db.Integer)
    Tmin = db.Column(db.Integer)
