from bicycles import db

class BicycleCount(db.Model):
    x = db.Column(db.Numeric)
    y = db.Column(db.Numeric)
    objectid = db.Column(db.Integer)
    recordnum = db.Column(db.Integer, primary_key=True)
    setdate = db.Column(db.DateTime)
    setyear = db.Column(db.Integer)
    comments = db.Column(db.Text)
    mcd = db.Column(db.BigInteger)
    route = db.Column(db.Integer)
    road = db.Column(db.Text)
    cntdir = db.Column(db.String)
    fromlmt = db.Column(db.Text)
    tolmt = db.Column(db.Text)
    type = db.Column(db.Text)
    latitude = db.Column(db.Numeric)
    longitude = db.Column(db.Numeric)
    factor = db.Column(db.Integer)
    axle = db.Column(db.Float)
    outdir = db.Column(db.String(1))
    indir = db.Column(db.String(1))
    aadb = db.Column(db.Integer)
    updated = db.Column(db.DateTime)
    co_name = db.Column(db.Text)
    mun_name = db.Column(db.Text)
    globalid = db.Column(db.Text)
    program = db.Column(db.Text)
    bikepedgro = db.Column(db.Text)
    bikepedfac = db.Column(db.Text)
    geom = db.Column(db.Text)


class Weather(db.Model):
    station = db.Column(db.Text)
    name = db.Column(db.Text)
    date = db.Column(db.Date, primary_key=True)
    prcp = db.Column(db.Float)
    tavg = db.Column(db.Integer)
    tmax = db.Column(db.Integer)
    tmin = db.Column(db.Integer)
